language: android

sudo: false

cache:
  directories:
    - $HOME/.gradle

android:
  components:
    - build-tools-23.0.1
    - android-23
    - sys-img-armeabi-v7a-android-21
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

script:
  - ./gradlew clean build install